### ISSUE TITLE
Milestone1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_Alberta-Oil-Spills#31]
**You may close this issue when all issues are resolved and checked.** 

**Reasoning**
- Great intro!
- [x] May you describe some of the variables, especially the substance, volume, and year_quarter? What is substance? What are the units? Type of variable?

**Visualization**
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not have to refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"
- [x] Add units to axis. 
- [x] Figure 7 is hard to read. 

**Quality -- Readability and Documentation**
- [x] Need a usage example in 3_model_fitting.py. Usage example in other scripts should include arguments. 
- [x] Odd white spacing in scripts. Makes the code harder to read. 

**Quality -- Robustness and Maintainability**
- [x] Should have a unit test in each script (because we did not clearly mention this in the instructions, we did not deduct points for not having a unit test)

**Grammar and Spelling**
- [x] Misspelled occurred
> Due to the large difference in number of..

- [x] Missing definite article "the" before number

**Comment by huijuechen** [comment]
update for the checked issues.

**Comment by huijuechen** [comment]
update for the checked issues.

Regarding the comment "Add units to axis", as other than the first figure, which is a counting of the occurrence( so no unit?), the rest of all our figures are using proportion, so I suppose there is no unit either?

**Comment by alyciakb** [comment]
- Updated all figure captions.

**Regarding figure 7:**

- We are unsure how to break our decision tree into components to make it easier to read, but I added a more descriptive figure caption and added a note that if the reader zooms in, they will be able to read the tree better.

**Regarding unit tests:**

- We haven't learned unit tests. We will try to add them in for the final project next week, however we don't currently know how to do unit tests or what they are.

**Comment by aimirza** [comment]
You wrote some testing in DSCI 511 lab 4 https://github.ubc.ca/MDS-2018-19/DSCI_511_prog-dsci_students/blob/master/release/lab4/lab4.ipynb

Only write unit tests for function you created other than the main function. A simple test is to ensure that a dataframe is provided where the columns are features for example. If you have to use statistics to generate your plot you can use a unit test similar to this example: https://stackoverflow.com/questions/27948126/how-can-i-write-unit-tests-against-code-that-uses-matplotlib

Hope this helps.

**Comment by aimirza** [comment]
> update for the checked issues.
> 
> Regarding the comment "Add units to axis", as other than the first figure, which is a counting of the occurrence( so no unit?), the rest of all our figures are using proportion, so I suppose only for the volume figure (Figure 6) x axis you are referring to?

Hmm, I dont see any issues with your axes... Maybe I was refering to fig 6 but you did have units for it. Please ignore

**Comment by aimirza** [comment]
> * Updated all figure captions.
> 
> **Regarding figure 7:**
> 
> * We are unsure how to break our decision tree into components to make it easier to read, but I added a more descriptive figure caption and added a note that if the reader zooms in, they will be able to read the tree better.
> 

Text in decision tree graphic is far too small to be useful. Could simplify if by rotating it 90 degrees (more room for bigger text!) and including less info on the graphic (value, samples and gini could be in a table in an appendix). (Tiffany's comment). In addition, you can reduce the levels to 3 instead of 4.

**Comment by huijuechen** [comment]
- Added unit test
- Update decision tree graphic to horizontal to make it more readable (instead of decrease the max depth)
